# Generated by Django 3.0.8 on 2020-09-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200903_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ISBN',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
